version: '3'

services:
  database:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
    - POSTGRES_USER=db_user
    - POSTGRES_PASSWORD=db_pass
    - POSTGRES_DB=prototype_database
    container_name: prototype_db_container
    ports:
    - 1015:5432
  prototype:
    build:
      context: .
      dockerfile: prototype.dockerfile
    container_name: prototype_container
    ports:
      - 2999:8000
    environment:
      - DB_USER=db_user
      - DB_PASS=db_pass
      - DB_NAME=prototype_database
      - DB_HOST=database
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=WIfxHMwA095VLMMbU5zFrg1VpMlCGLpNc98jI
      - SUPERUSER_NAME=admin
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASS=pass
    links:
      - database
    depends_on:
      - database
  simulator:
    build:
      context: .
      dockerfile: simulator.dockerfile
    container_name: prototype_simulator
    ports:
      - "8089:8089"
    links:
      - prototype
    depends_on:
      - prototype
