version: '3'

services:
  pg_database:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
    - POSTGRES_USER=db_user
    - POSTGRES_PASSWORD=db_pass
    - POSTGRES_DB=prototype_database
    container_name: prototype_db_container
    ports:
    - 1015:5432
  prototype:
    build:
      context: .
      dockerfile: prototype.dockerfile
    container_name: prototype_container
    ports:
      - 2999:8000
    environment:
      - DB_USER=db_user
      - DB_PASS=db_pass
      - DB_NAME=prototype_database
      - DB_HOST=pg_database
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=WIfxHMwA095VLMMbU5zFrg1VpMlCGLpNc98jI
      - SUPERUSER_NAME=admin
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASS=pass
    links:
      - pg_database
    depends_on:
      - pg_database
  simulator:
    build:
      context: .
      dockerfile: simulator.dockerfile
    container_name: prototype_simulator
    environment:
      - HOST=prototype
      - PORT=8000
      - USERS_NUM=90
      - HATCH_RATE=2
    links:
      - prototype
    depends_on:
      - prototype
  pg_target_database:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
    - POSTGRES_USER=db_user
    - POSTGRES_PASSWORD=db_pass
    - POSTGRES_DB=prototype_dwh
    container_name: prototype_dwh
    ports:
    - 1020:5432
